# Generated by Django 5.1.1 on 2025-03-04 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_street_address', models.CharField(max_length=100)),
                ('secondary_street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FLAVOUR', 'Flavour'), ('EXTRA', 'Extra')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('associated_flavour', models.ForeignKey(blank=True, help_text='Associate this extra with a flavour.', limit_choices_to={'category': 'FLAVOUR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='core.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_time_of_arrival', models.DateTimeField()),
                ('customer_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.customer')),
                ('order_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orderaddress')),
                ('items', models.ManyToManyField(related_name='orders', to='core.orderitem')),
            ],
        ),
    ]
