# Generated by Django 5.1.1 on 2024-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('FLAVOUR', 'Flavour'), ('EXTRA_HEAD', 'Extra_Head')], max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_address', models.CharField(max_length=255)),
                ('estimated_time_of_arrival', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(related_name='orders', to='core.orderitem')),
            ],
        ),
    ]
