# Generated by Django 5.1.1 on 2024-12-11 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_street_address', models.CharField(max_length=100)),
                ('secondary_street_address', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message="Enter a valid postal code in the format of 'A1A '1A1'.", regex='^[A-Za-z]\\d[A-Za-z] \\d[A-Za-z]\\d$')])),
                ('city', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.orderaddress'),
        ),
    ]
