# Generated by Django 5.1.1 on 2024-12-17 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderitem_associated_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='associated_flavour',
            field=models.ForeignKey(blank=True, help_text='Associate this extra with a flavour.', limit_choices_to={'category': 'FLAVOUR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='core.orderitem'),
        ),
    ]
