# Generated by Django 5.1.1 on 2024-12-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_orderitem_associated_flavour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='estimated_time_of_arrival',
            new_name='expected_time_of_arrival',
        ),
    ]
