# Generated by Django 5.1.1 on 2025-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_estimated_time_of_arrival_order_expected_time_of_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(max_length=7),
        ),
    ]
